/*LIBERANDO O SAFE MODE PARA REALIZAR UPDATE*/
SET SQL_SAFE_UPDATES = 0;

/*CREANDO BANCO DE DADOS*/
CREATE DATABASE NOME_BANCO_DADOS;

/*MOSTRANDO TODOS OS BANCO DE DADOS*/
SHOW DATABASES;

/*USANDO UM BANCO DE DADOS*/
USE NOME_BANCO_DADOS;

/*MOSTRANDO TODAS AS TABELAS EM UM BANCO DE DADOS*/
SHOW TABLES;