/*MOSTRANDO TODOS OS BANCO DE DADOS*/
SHOW DATABASES;

/*USANDO UM BANCO DE DADOS*/
USE NOME_BANDO_DADOS;

/*SELECIONANDO DADOS DE UMA TABELA */
SELECT * FROM NOME_TABELA;

/*SELECIONANDO UM BANCO DE DADOS E UMA TABELA*/
SELECT * FROM NOME_DATABASE.NOME_TABELA;
