/*MOSTRANDO TODOS OS BANCO DE DADOS*/
SHOW DATABASES;

/*USANDO UM BANCO DE DADOS*/
USE NOME_BANDO_DADOS;

/*SELECIONANDO TODOS OS DADOS DE UMA TABELA NO BANCO DE DADOS */
SELECT * FROM NOME_TABELA;

/*SELECIONANDO TODOS OS DADOS DE UMA TABELA NO BANCO DE DADOS */
SELECT * FROM NOME_DATABASE.NOME_TABELA;