/* USANDO UM BANCO DE DADOS*/
USE pessoas;

/* CREANDO TABELA TIPO DE DAODS TEXTO*/
CREATE TABLE teste (nome VARCHAR (100), sobrenome VARCHAR (100), cpf CHAR (11), rg CHAR (8));

/* CRIANDO TABELA TIPO DE DADOS NUMERICO*/
CREATE TABLE servidores (nome VARCHAR(100), capacidade INT(10), ligado BOOL);

/*CRIANDO TIPOS DE DADOS DATA */
CREATE TABLE aniversario (nome VARCHAR(100), nascimento DATE);

/*CRIANDO TABELA COM OS DADOS: TEXTO, NUMERICOS, DATA*/
CREATE TABLE pessoas 
(nome VARCHAR (100), sobrenome VARCHAR(100), cpf CHAR(11), aniversario DATE, limite INT(10));

/*SELECIONANDO TODOS OS DADOS DE UMA TABELA NO BANCO DE DADOS */
SELECT * FROM pessoas;