/*USANDO BANCO DE DADOS*/
USE empresa;

/*MOSTRANDO TODOS OS DADOS DE UMA TABELAS DO BANCO DE DADOS*/
SHOW TABLES;

/*SELECIONANDO TODOS OS DADOS DE UMA TABELA NO BANCO DE DADOS */
SELECT * FROM empresa.teste;

/*ALTERANDO UMA TABELA E ADICIOANDO UMA COLUNA NA TABELA*/
ALTER TABLE teste ADD COLUMN anivercario DATE;

/*INSERINDO DADOS EM UMA TABELA*/
INSERT INTO teste (nome, sobrenome, cpf, rg, anivercario) VALUES 
('Carlos','Fernandes','12345678960','12345678','1990-01-01'),
('Renata','Silva Fernandes','12345678960','12345678','1990-01-01');

/*ALTERANDO TABELA E ADICIONANDO UMA COLUNA*/
ALTER TABLE teste ADD COLUMN ativo DATE;