/*USANDO UM BANCO DE DADOS*/ 
USE cadastro;

/*SELECIONANDO TODOS OS DADOS TABELA NO BANCO DE DADOS*/
SELECT * FROM pessoas;

/*ALTERANDO TABELA E ADICIONANDO UMA COLUNA*/
ALTER TABLE pessoas ADD COLUMN ativo DATE;

/* MODIFICANDO O DADO DE UMA COLUNA*/
ALTER TABLE pessoas MODIFY COLUMN ativo BOOL;