/*USANDO UM BANCO DE DADOS*/ 
USE cadastro;

/*SELECIONANDO TODOS OS DADOS TABELA NO BANCO DE DADOS*/
SELECT * FROM pessoas;

/*SELECIONANDO ALGUMAS COLUNAS DE UMA TABELA DO BANCO DE DADOS*/
SELECT nome, aniversario FROM pessoas;