/*USANDO UM BANCO DE DADOS*/ 
USE cadastro;

/*SELECIONANDO TODOS OS DADOS TABELA NO BANCO DE DADOS*/
SELECT * FROM pessoas;

/* SELECIONANDO OS DADOS EXPECIFICO EM UMA TABELA*/
SELECT * FROM pessoas WHERE nome = 'Douglas';