/*USANDO UM BANCO DE DADOS*/ 
USE cadastro;

/*SELECIONANDO TODOS OS DADOS TABELA NO BANCO DE DADOS*/
SELECT * FROM pessoas;
SELECT * FROM pessoas WHERE nome = 'Douglas';

/*DELETANDO UM DADO DE UMA TABELA NO BANCO DE DADOS*/
DELETE FROM pessoas WHERE nome = 'Douglas';
DELETE FROM pessoas WHERE limite < 5000;

/*DELETANDO TODO CONTEUDO DE UMA TABELA*/
DELETE FROM pessoas;