/*USANDO UM BANCO DE DADOS*/ 
USE employees;

/*MOSTRANDO TODAS AS TABELAS DE UM BANCO DE DADOS*/
SHOW TABLES;

/*SELECIONANDO TODOS OS DADOS TABELA NO BANCO DE DADOS*/
SELECT * FROM salaries;
SELECT * FROM salaries WHERE salary >= 65000