/*USANDO UM BANCO DE DADOS*/ 
USE employees;

/*SELECIONANDO TODOS OS DADOS DE UMA TABELA*/
SELECT * FROM titles;

/*SELECIONANDO DADOS DISTINTOS DE UMA COLUNA ESPECIFICA*/
SELECT DISTINCT title FROM titles;
