/*USANDO UM BANCO DE DADOS*/ 
USE employees;

/*SELECIONANDO TODOS OS DADOS DE UMA TABELA*/
SELECT * FROM salaries;

/*SELECIONANDO TODOS DOS DADOS DE UMA COLUNA USANDO O AND */
SELECT * FROM salaries WHERE salary < 70000 AND from_date > '1991-12-12' AND emp_no = 12800;